version: '3.8'

services:
  backend:
    container_name: fillin
    image: ${DOCKERHUB_USERNAME}/fillin:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    expose:
      - "8080:8080"
    networks:
      - fillin_network
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - fillin_network
    restart: always

networks:
  fillin_network:
    driver: bridge