# 1) HTTP: 인증서 갱신용 + 리다이렉트
server {
    listen 80;
    server_name api.fillin.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 2) HTTPS: 실제 서비스
server {
    listen 443 ssl;
    server_name api.fillin.site;

    ssl_certificate     /etc/letsencrypt/live/api.fillin.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.fillin.site/privkey.pem;

    location = / {
        default_type text/plain;
        return 200 "Server is running\n";
    }
    # 모든 요청을 스프링 부트(backend 컨테이너)로 토스
    location / {
        proxy_pass http://backend:8080; # docker-compose의 서비스 이름 사용
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /swagger-ui/ {
        proxy_pass http://backend:8080/swagger-ui/;
        proxy_set_header Host $host;
    }
    location /v3/api-docs {
        proxy_pass http://backend:8080/v3/api-docs;
        proxy_set_header Host $host;
    }
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}